#!/usr/bin/env bash
set -e

tmpdir=$(mktemp -d)
CACHE_DIR=/srv/cache/srv/git/envygeeks.io.git
GIT_WORK_TREE=$tmpdir git checkout -f master
cd $tmpdir

# --

cp -RTp $CACHE_DIR .
docker-compose -f compose.yml pull >/dev/null
docker-compose -f compose.yml run production-build
rsync -av --delete --quiet _site/ /srv/docker/envygeeks/srv/nginx/envygeeks.io
docker-compose -f compose.yml rm -f --all

# --
# Update the caches with the latest stuff that we get when
# building out the current site, this will rarely get updated
# but it does none-the-less, so we need to make sure that we
# keep it updated.
# --

mkdir -p $CACHE_DIR/vendor/bundle
docker-compose -f compose.yml run update
rsync -av --quiet --delete vendor/bundle/ \
  $CACHE_DIR/vendor/bundle

# --

rm -rf $tmpdir
cd -

# --
# Cleanup if the function docker-clean is available.
# This is provided by our server, but there is a public
# version somebody else made somewhere.
# --

docker-clean 2>/dev/null \
  || true
