# Frozen-string-literal: true
# Copyright: 2017 Jordon Bedwell - MIT License
# Encoding: utf-8

source "https://rubygems.org"
gemspec

group :development do
  gem "pry", require: false
  gem "rubocop", require: false
  gem "rake", require: false

  group :test do
    gem "rspec", require: false
  end
end
