#!/usr/bin/env ruby
# Frozen-String-Literal: true
# Encoding: utf-8

require 'fileutils'
require 'bundler/setup'
require 'pathutil'
require 'pry'

base = Pathutil.pwd.join('dist')
base.glob('**/index.html').map do |file|
  next if file.dirname == base
  file.rename(file.dirname.sub_ext('.html'))
  file.dirname.rm_rf if file.dirname
    .children.empty?
end
