#!/bin/bash -l
. script/base/env
set -e

HOSTNAME=envygeeks.io
DEPLOY_TO=/srv/nginx/envygeeks.io
DEPLOY_USER=jordon
FOLDER=site/

if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
  if [ "$CI" = "true" ]; then
    mkdir -p ~/.ssh
    openssl aes-256-cbc -K $encrypted_254287a454b2_key \
      -iv $encrypted_254287a454b2_iv -in script/files/deploy.key.enc \
      -out ~/.ssh/id_rsa -d
  fi

  rsync -avz $FOLDER $DEPLOY_USER@$HOSTNAME:$DEPLOY_TO
fi
