#!/bin/bash -l
. script/base/env
set -e

KEY=~/.ssh/id_rsa
DEPLOY_HOST=${DEPLOY_HOST:=envygeeks.io}
DEPLOY_TO=${DEPLOY_TO:=/srv/nginx/envygeeks.io}
DEPLOY_USER=${DEPLOY_USER:=jordon}
FOLDER=site/

if [ "$CI" = "true" ]; then
  mkdir -p ~/.ssh
  openssl aes-256-cbc -K $encrypted_254287a454b2_key \
    -iv $encrypted_254287a454b2_iv \
    -in script/file/deploy.key.enc \
    -out $KEY -d

  chmod og-rwx $KEY
fi

for ip in $(dig +short $DEPLOY_HOST); do
  # So that if we have multiple hosts, they all get it.
  rsync -avz $FOLDER --delete $DEPLOY_USER@$ip:$DEPLOY_TO
done
