#!/bin/bash -l
. script/base/env
set -e

KEY=~/.ssh/id_rsa
HOSTNAME=envygeeks.io
DEPLOY_TO=/srv/nginx/envygeeks.io
DEPLOY_USER=jordon
FOLDER=site/

if [ "$CI" = "true" ]; then
  mkdir -p ~/.ssh
  openssl aes-256-cbc -K $encrypted_254287a454b2_key \
    -iv $encrypted_254287a454b2_iv \
    -in script/file/deploy.key.enc \
    -out $KEY -d

  chmod og-rwx $KEY
fi

# --
# TODO: In this future this will probably sync directly to
#   GCS rather than GCE, and then GCE will probably downstream from
#   that service caching everything and speeding it up a bit.
# --

echo "Uploading files to $HOSTNAME"
rsync -avz $FOLDER --delete $DEPLOY_USER@$HOSTNAME:$DEPLOY_TO
echo "Done uploading"
