#!/bin/bash
set -e

# --
prec=""
test=$(docker info 2>&1 || true)
echo $test | grep -q "permission" \
  && prec="sudo"

# --
if [ "$1" = "pull" ]; then
  $prec docker pull jekyll/jekyll:latest
  $prec docker system prune -f
else
  $prec docker run --rm \
    --volume=$PWD/vendor/bundle:/usr/local/bundle \
    --volume=$PWD:/srv/jekyll \
    \
    --env="DEBUG=$DEBUG" \
    --env="JEKYLL_ENV=$JEKYLL_ENV" \
    --env="GITHUB_TOKEN=$GITHUB_TOKEN" \
    --env="CONNECTED=$CONNECTED" \
    --env="JEKYLL_UID=$UID" \
    --env="CI=$CI" \
    \
    --publish="127.0.0.1:4000:4000" \
    --publish="127.0.0.1:35729:35729" \
    --publish="127.0.0.1:3000:4000" \
    \
    -it jekyll/jekyll:latest \
      "$@"
fi
