#!/bin/sh
[ "$DEBUG" = true ] && set -x
set -e

echo 'minifying html for http performance on slow networks'
npx html-minifier --output-dir=dist/ --input-dir=dist/ --file-ext=html \
  --minify-js --minify-css --remove-comments --collapse-whitespace --remove-tag-whitespace \
  --collapse-boolean-attributes --remove-style-link-type-attributes \
  --remove-script-type-attributes --remove-redundant-attributes \
  --remove-attribute-quotes --quote-character=\"
echo 'cleaning up and compressing css output'
npx postcss dist/assets/css/*.css -r
