#!/bin/sh
[ "$DEBUG" = true ] && set -x
set -e

npx html-minifier --output-dir=dist/ \
  --input-dir=dist/ --file-ext=html --minify-js --minify-css \
  --remove-comments --collapse-whitespace --remove-tag-whitespace \
  --collapse-boolean-attributes --remove-style-link-type-attributes \
  --remove-script-type-attributes --remove-redundant-attributes \
  --remove-attribute-quotes --quote-character=\"
