#!/bin/bash -l
. script/base/env
set -e

if [ -d site ]; then
  node_modules/.bin/postcss --no-map --config=script/file/postcss.js 2> \
  /dev/null site/assets/*.css --dir=site/assets || true
  node_modules/.bin/html-minifier $args --output-dir=site/ \
    --input-dir=site/ --file-ext=html --html5 --minify-js --minify-css \
    --remove-comments --collapse-whitespace --remove-tag-whitespace \
    --collapse-boolean-attributes --remove-style-link-type-attributes \
    --remove-script-type-attributes --remove-redundant-attributes \
    --remove-attribute-quotes --quote-character=\"
fi
