name: Build Docker Image
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - uses: actions/docker/cli@master
      with:
        args: build -t envygeeks/website:latest .
    - uses: actions/docker/cli@master
      with:
        args: push envygeeks/website:latest
