name: 'Continuous Integration'
on:
  push:
    branches:
      - master
jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1 
      with:
        node-version: '10.x'
    - run: npm install
    - run: npx gridsome build
