name: 'Build, Test, and Deploy'
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: aactions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm install
    - run: npx gridsome build
