name: 'Continuous Integration'
on:
  - pull_request
  - push
jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.x'
      - run: npm install
      - run: bundle install --path vendor/bundle
      - run: script/build
      - run: script/cleanup
      - run: script/minify
      - uses: actions/upload-artifact@master
        with:
          name: website
          path: dist/
  deploy:
    name: 'Deploy'
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    env:
      DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
      DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
      DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
    needs:
      - build
    steps:
      - uses: actions/checkout@v1
      - uses: actions/download-artifact@master
        with:
          name: website
          path: dist/
      - run: mkdir -p "${HOME}/.ssh"
      - run: chmod og-rwx "${HOME}/.ssh"
      - run: echo "${DEPLOY_KEY}" | tee "${HOME}/.ssh/id_rsa"
      - run: script/deploy
